# Generated by Django 4.1.7 on 2023-11-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
