# Generated by Django 4.1.7 on 2023-11-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_orderstatus_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='price',
        ),
    ]
