# Generated by Django 4.1.7 on 2023-11-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_total_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='Shipped', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderstatus'),
        ),
    ]
