# Generated by Django 4.1.7 on 2023-11-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
