# Generated by Django 4.1.7 on 2023-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
