# Generated by Django 4.1.7 on 2023-11-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
    ]
